
services:
  mongodb:
    container_name: mongo_container
    image: bitnami/mongodb:latest
    restart: unless-stopped
    environment:
      - MONGODB_USERNAME=ankit
      - MONGODB_PASSWORD=password123
      - MONGODB_ROOT_PASSWORD=admin123
      - MONGODB_DATABASE=todo_app

    ports:
      - "27017:27017"
    volumes:
      - "./docker/mongodb_data:/bitnami/mongodb"
    networks:
      - custom_network

  redis:
    image: redis:latest
    container_name: redisdb_container
    ports:
      - "6379:6379"
    volumes:
      - "./docker/redis_data:/data"
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
volumes:
  mongodb_data:
    driver: local